### PR TITLE
chore: add standard venv names and notebook checkpoints to gitignore

### PR DESCRIPTION
**Pull request by phinate**
Tiny little PR for quality of life when people make venvs to look at cabinetry :)

feel free to do yourself if you don't want to give me easy contributor status ;)

### CODE REVIEW

**Comment by alexander-held** [comment]
Thanks, this is very useful to have! The CI issue is unrelated and another instance of #199, I will get that fixed separately.

**Comment by phinate** [comment]
fwiw, I think these and more are covered in github's standard python template, may be worth looking at: https://github.com/github/gitignore/blob/master/Python.gitignore

**Review by alexander-held — COMMENTED** [review]
The CI issue should be fixed after rebasing on master. I had a look at the template you linked and would suggest adding `.ipynb_checkpoints` to this PR. Happy to extend the gitignore further if required in practice.

**Comment by phinate** [comment]
should be good now!

**Comment by alexander-held** [comment]
The CI fails during Codecov upload, which should have been fixed by #230 upon which this branch is based. It is currently unclear to me why the token is not picked up in the CI here.

**Comment by alexander-held** [comment]
This is likely related to https://github.com/codecov/codecov-action/issues/330, so let's see whether it can get resolved centrally. The fact that #230 worked fine may have just been a lucky coincidence.

**Comment by alexander-held** [comment]
Independent of Codecov, the release of `mypy` 0.900 requires another small update which will go in via https://github.com/alexander-held/cabinetry/pull/232. With that done and Codecov stabilized, it should then be able to get CI to pass here again.

**Comment by alexander-held** [comment]
With #232 done this PR now passed CI as well. Thanks for the contribution!

**Pull request merged**
